### ISSUE TITLE
Missing model and view version in PivotUIBox

### ISSUE THREAD

**Issue by oscar6echo** [PierreMarion23/pivot-table-widget#5]
Without them, the rendering of ipypivot in nbviewer does not work.  
What happens is that the PivotUIBox model and view versions gets a default (I suspect) 1.1.0.  
The corresponding npm package does not exist and the CDN download https://unpkg.com/ipypivot@1.1.0/dist/index.js fails.  

To see how it's broken see this [nbviewer-test repo](https://github.com/oscar6echo/nbviewer-test).  
In particular:
+  [this notebook](https://nbviewer.jupyter.org/github/oscar6echo/nbviewer-test/blob/master/demo_ipypivot_very_short.ipynb) containing only Pivot, properly rendered.  
+ [this notebook](https://nbviewer.jupyter.org/github/oscar6echo/nbviewer-test/blob/master/demo_ipypivot_short_2.ipynb), where neither Pivot not PivotUI are rendered. Open console: CDN links are broken

**Comment by oscar6echo** [comment]
Cf. my 6 commits today to correct the issue.  
The Python package new version 0.2.6 need be pushed on pypi.org.  
The Javascript package new version 0.1.1 need be pushed on npmjs.org.

**Comment by PierreMarion23** [comment]
Thanks, the packages have been pushed.
