### ISSUE TITLE
basic example not working

### ISSUE THREAD

**Issue by bernardotrek** [PierreMarion23/pivot-table-widget#8]
Hello

I tried to use your widget but I cant even run the first example you provide. Could you help? thx
---------------------------------------------------------------------------
**TypeError                                 Traceback (most recent call last)
<ipython-input-3-4b02b794ce75> in <module>()
      2 import ipypivot as pt
      3 
----> 4 p = pt.Pivot(df_data=df)

/anaconda2/lib/python2.7/site-packages/ipypivot/_widget_pivot.pyc in __init__(self, df_data)
     31         """
     32         """
---> 33         super().__init__()
     34         self.options = Pivot_Options(self)
     35** 

**TypeError: super() takes at least 1 argument (0 given)**

**Comment by oscar6echo** [comment]
Thanks for your interest.

From the stack trace I see that you run Python 2.7.
But ipypivot [only support Python 2](https://github.com/PierreMarion23/ipypivot/blob/c8669fe37a188f587f3c75f7382a4d857a32fe33/setup.py#L57).  
We do not plan to support Python 2.7 as it is [on the way out](https://pythonclock.org/).
