### ISSUE TITLE
Is this repo maintained any longer  ? Pandas version requirements needs to be updated !!

### ISSUE THREAD

**Issue by bytesemantics** [PierreMarion23/pivot-table-widget#9]
This remains a very useful project - being the only ipywidget wrapper of  pivottable.js  that I've managed to find.

Unfortunately its  proving more and more difficult to install due to competing and incompatible pandas library version requirements when used with other python packages.

A compelling reason for using this btw - is that the widget renders correctly when using voila (pivottable_js implementations do not render in voila which expects notebook widget extensions for each 'widget' to be output).

**Comment by dschofield** [comment]
Thanks for confirming compatibility with Voila. Given that, I'd be willing to take a look and see what updates are necessary. It would be good to hear from @PierreMarion23 before forking.

**Comment by bytesemantics** [comment]
I've pulled the code and can confirm it works with Pandas V1.2.1.
I replaced pandas condition requirement from == to >=

**Comment by PierreMarion23** [comment]
Hi there,
Thanks for pinging me and sorry for the delay. I will take a look later today, and update the pandas condition requirement, as suggested by @bytesemantics.

**Comment by PierreMarion23** [comment]
I published version 0.2.7 of the package on PyPI, with the updated pandas version. pip installing it should work. Please tell me  if this didn't solve your issue.

**Comment by fiatluxadmin** [comment]
> I published version 0.2.7 of the package on PyPI, with the updated pandas version. pip installing it should work. Please tell me if this didn't solve your issue.

I'll be doing some testing with this today and will report back status. Thanks for addressing this so promptly, much appreciated.

**Comment by PierreMarion23** [comment]
The package version 0.2.7 has also been uploaded to Anaconda Cloud. I am closing the issue. Feel free to reopen if necessary.
